// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojT4Ezgh3WQpJ7us1a-m23RJvUqzgtf4',
    appId: '1:328780703163:android:fef9e069d675ba8ed8109e',
    messagingSenderId: '328780703163',
    projectId: 'ng-complete-guide-87e4f',
    databaseURL: 'https://ng-complete-guide-87e4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ng-complete-guide-87e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDehEu09Fuc2PGwLk3kf9HftJRcHQL1X1M',
    appId: '1:328780703163:ios:a2ed331acff255b0d8109e',
    messagingSenderId: '328780703163',
    projectId: 'ng-complete-guide-87e4f',
    databaseURL: 'https://ng-complete-guide-87e4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ng-complete-guide-87e4f.appspot.com',
    iosClientId: '328780703163-4mj5giffa5vjb46r2tvb4s9ltfr75d4m.apps.googleusercontent.com',
    iosBundleId: 'be.codelearner.mynotes',
  );
}
